
# WARNING: DO NOT EDIT THIS FILE BY HAND.  IT IS AUTO-GENERATED!
module Bundler
  module Audit
    class Database
      VENDORED_REPO_CTIME = Time.parse("Wed Oct 23 11:22:06 2013 -0400")
    end
  end
end
